spring.application.name=mdClone
#enabling the H2 console
spring.datasource.url=jdbc:h2:mem:mdClone
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.data.jpa.repositories.bootstrap-mode=default
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.fail-on-empty-beans=false
